package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseAdminRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRoleMenu extends BaseAdminRoleMenu<AdminRoleMenu> {
	
}
