package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseAdminRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRole extends BaseAdminRole<AdminRole> {

	/**
	 * 判断是否为超级管理员
	 * 
	 * @param id
	 * @return
	 */
	public static boolean isSuperAdmin(int id) {
		return id == 1;
	}
}
