package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseAdminPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminPermission extends BaseAdminPermission<AdminPermission> {
	
}
