package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseAdminRolePremission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRolePremission extends BaseAdminRolePremission<AdminRolePremission> {
	
}
