package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseAdminMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminMenu extends BaseAdminMenu<AdminMenu> {

	/**
	 * 是否是根菜单
	 * 
	 * @return
	 */
	public boolean isRoot() {
		return getParentId() == 0;
	}
}
