package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseAdminUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminUserRole extends BaseAdminUserRole<AdminUserRole> {
	
}
