package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseAdminRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRolePermission extends BaseAdminRolePermission<AdminRolePermission> {
	
}
