package top.chengdongqing.common.model;

import java.lang.reflect.Field;

import top.chengdongqing.common.model.base.BaseBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Banner extends BaseBanner<Banner> {

	/**
	 * 横幅类型
	 */
	public interface Type {
		// 滚动轮播图
		String SLIDE = "slide";
		// 推销商品广告
		String PROMO = "promo";
		// 商品广告横幅
		String ADVERT = "advert";
		// 商品类别广告
		String CATEGORY = "category";
		// 首页顶部横幅
		String TOP = "top";

		/**
		 * 判断指定的横幅类型是否存在
		 * 
		 * @param type
		 * @return
		 */
		public static boolean hasType(String type) {
			boolean hasType = false;
			try {
				for (Field field : Type.class.getDeclaredFields()) {
					String value = field.get(field.getName()).toString();
					if (type.equals(value)) {
						hasType = true;
						break;
					}
				}
			} catch (IllegalArgumentException | IllegalAccessException e) {
				e.printStackTrace();
			}
			return hasType;
		}
	}
}
