package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cart extends BaseCart<Cart> {
	
}
