package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseGoodsAttrValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsAttrValue extends BaseGoodsAttrValue<GoodsAttrValue> {
	
}
