package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseGoodsCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsCategory extends BaseGoodsCategory<GoodsCategory> {

	/**
	 * 是否是根类别
	 * 
	 * @return
	 */
	public boolean isRoot() {
		return getParentId() == 0;
	}
}
