package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseGoodsAttrKey;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsAttrKey extends BaseGoodsAttrKey<GoodsAttrKey> {
	
}
