package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseGoodsComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsComment extends BaseGoodsComment<GoodsComment> {
	
}
