package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {

	/**
	 * 是否有多规格
	 * 
	 * @return
	 */
	public boolean hasVariousSpec() {
		return getSkuType() == 1;
	}
}
