package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseGoodsBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsBanner extends BaseGoodsBanner<GoodsBanner> {
	
}
