package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseGoodsBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsBrand extends BaseGoodsBrand<GoodsBrand> {
	
}
