package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseOrderGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderGoods extends BaseOrderGoods<OrderGoods> {
	
}
