package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseOrderAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderAddress extends BaseOrderAddress<OrderAddress> {
	
}
