package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseOrderTime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderTime extends BaseOrderTime<OrderTime> {
	
}
