package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseOrderExpress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderExpress extends BaseOrderExpress<OrderExpress> {
	
}
