package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {

	/**
	 * 订单状态枚举
	 */
	public enum Status {
		ORDERED(0, "待付款"), PAID(2, "已付款"), PREPARED(4, "已配货"), //
		SHIPPED(6, "已发货"), RECEIPTED(8, "已收货"), COMMENTED(10, "已评价"), //
		REFUNDING(30, "退款中"), REFUNDED(32, "已退款"), REFUND_FAIL(34, "退款失败"), CANCELED(40, "已取消");

		private Status(int code, String name) {
			this.code = code;
			this.name = name;
		}

		private int code;
		private String name;

		public int getCode() {
			return code;
		}

		public String getName() {
			return name;
		}

		public static String getNameByCode(int code) {
			for (Status status : values()) {
				if (status.getCode() == code) {
					return status.getName();
				}
			}
			return null;
		}
	}

	/**
	 * 付款方式枚举
	 */
	public enum PayMode {
		ALIPAY(0, "支付宝"), WECHAT_PAY(1, "微信支付");

		private PayMode(int code, String name) {
			this.code = code;
			this.name = name;
		}

		private int code;
		private String name;

		public int getCode() {
			return code;
		}

		public String getName() {
			return name;
		}

		public static String getNameByCode(Integer code) {
			if (code != null) {
				for (PayMode mode : values()) {
					if (mode.getCode() == code) {
						return mode.getName();
					}
				}
			}
			return null;
		}
	}
}
