package top.chengdongqing.common.model;

import com.jfinal.aop.Aop;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.ehcache.CacheKit;

import top.chengdongqing.common.config.Constant.CacheKey;
import top.chengdongqing.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

	private final static User dao = Aop.get(User.class);

	/**
	 * 是否禁用
	 * 
	 * @return
	 */
	public boolean isDisabled() {
		return this.getStatus() == 1;
	}

	/**
	 * 账号安全等级
	 */
	public interface securityLevel {
		// 没有设置密码
		int DANGEROUS = 0;
		// 没有绑定邮箱
		int ORDINARY = 1;
		// 安全
		int SAFE = 2;
	}

	/**
	 * 用户相关校验正则
	 */
	public interface Pattern {
		// 手机号
		String PHONE = "1\\d{10}";
		// 邮箱
		String EMAIL = "\\b(^['_A-Za-z0-9-]+(\\.['_A-Za-z0-9-]+)*@([A-Za-z0-9-])+(\\.[A-Za-z0-9-]+)*((\\.[A-Za-z0-9]{2,})|(\\.[A-Za-z0-9]{2,}\\.[A-Za-z0-9]{2,}))$)\\b";
		// 手机号或邮箱
		String ACCOUNT = PHONE + "|" + EMAIL;
		// 登录密码
		String PASSWORD = "\\w{8,20}";
		// 验证码
		String CAPTCHA = "\\d{6}";
		// 昵称
		String NAME = "[a-zA-Z\\u4E00-\\u9FA5][a-zA-Z0-9_\\u4E00-\\u9FA5]{1,20}";
	}

	/**
	 * 根据token获取用户信息
	 * 
	 * @param token
	 * @return
	 */
	public static User getLoginUser(String token) {
		if (StrKit.isBlank(token)) {
			throw new IllegalArgumentException("The token can not be blank");
		}

		// 从缓存获取用户信息
		User user = CacheKit.get(CacheKey.LOGIN_USER, token, () -> {
			// 缓存中不存在则去数据库查询
			String sql = "select * from `user` where token = ? limit 1";
			return dao.findFirst(sql, token);
		});
		
		// 判断该对象是否为空
		if (user != null && user.getExpireTime() != null) {
			// 判断token是否已过期
			if (user.getExpireTime().getTime() > System.currentTimeMillis()) {
				return user;
			}
		}
		return null;
	}
}
