package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseUserAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAddress extends BaseUserAddress<UserAddress> {
	
}
