package top.chengdongqing.common.model;

import top.chengdongqing.common.model.base.BaseVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Video extends BaseVideo<Video> {
	
}
