package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 用户id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户昵称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 用户昵称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 头像地址
	 */
	public void setAvatarUrl(java.lang.String avatarUrl) {
		set("avatarUrl", avatarUrl);
	}
	
	/**
	 * 头像地址
	 */
	public java.lang.String getAvatarUrl() {
		return getStr("avatarUrl");
	}

	/**
	 * 手机号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 邮箱地址
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮箱地址
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 登录密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 登录密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 登录密码盐值
	 */
	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	/**
	 * 登录密码盐值
	 */
	public java.lang.String getSalt() {
		return getStr("salt");
	}

	/**
	 * 安全等级 0.待设置密码 1.待完善邮箱 2.安全
	 */
	public void setSecurityLevel(java.lang.Integer securityLevel) {
		set("securityLevel", securityLevel);
	}
	
	/**
	 * 安全等级 0.待设置密码 1.待完善邮箱 2.安全
	 */
	public java.lang.Integer getSecurityLevel() {
		return getInt("securityLevel");
	}

	/**
	 * 性别 0.未知 1.男 2.女
	 */
	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	/**
	 * 性别 0.未知 1.男 2.女
	 */
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	/**
	 * 生日
	 */
	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}
	
	/**
	 * 生日
	 */
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	/**
	 * 地区
	 */
	public void setRegion(java.lang.String region) {
		set("region", region);
	}
	
	/**
	 * 地区
	 */
	public java.lang.String getRegion() {
		return getStr("region");
	}

	/**
	 * 个性签名
	 */
	public void setMotto(java.lang.String motto) {
		set("motto", motto);
	}
	
	/**
	 * 个性签名
	 */
	public java.lang.String getMotto() {
		return getStr("motto");
	}

	/**
	 * 状态 0.正常 1.冻结
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 0.正常 1.冻结
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 登录后的令牌
	 */
	public void setToken(java.lang.String token) {
		set("token", token);
	}
	
	/**
	 * 登录后的令牌
	 */
	public java.lang.String getToken() {
		return getStr("token");
	}

	/**
	 * token过期时间
	 */
	public void setExpireTime(java.util.Date expireTime) {
		set("expireTime", expireTime);
	}
	
	/**
	 * token过期时间
	 */
	public java.util.Date getExpireTime() {
		return get("expireTime");
	}

	/**
	 * 最后登录时间
	 */
	public void setLoggedTime(java.util.Date loggedTime) {
		set("loggedTime", loggedTime);
	}
	
	/**
	 * 最后登录时间
	 */
	public java.util.Date getLoggedTime() {
		return get("loggedTime");
	}

	/**
	 * 最后登录的设备ip地址
	 */
	public void setLoggedIp(java.lang.String loggedIp) {
		set("loggedIp", loggedIp);
	}
	
	/**
	 * 最后登录的设备ip地址
	 */
	public java.lang.String getLoggedIp() {
		return getStr("loggedIp");
	}

	/**
	 * 注册来源 0.pc平台 1.app平台 2.小程序平台 3.手机H5平台 4.管理平台
	 */
	public void setCreateFrom(java.lang.Integer createFrom) {
		set("createFrom", createFrom);
	}
	
	/**
	 * 注册来源 0.pc平台 1.app平台 2.小程序平台 3.手机H5平台 4.管理平台
	 */
	public java.lang.Integer getCreateFrom() {
		return getInt("createFrom");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setThirdId(java.lang.String thirdId) {
		set("thirdId", thirdId);
	}
	
	public java.lang.String getThirdId() {
		return getStr("thirdId");
	}

	public void setLoginType(java.lang.Integer loginType) {
		set("loginType", loginType);
	}
	
	public java.lang.Integer getLoginType() {
		return getInt("loginType");
	}

}
