package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVideo<M extends BaseVideo<M>> extends Model<M> implements IBean {

	/**
	 * 视频id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 视频id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 视频名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 视频名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 视频介绍
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 视频介绍
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 视频封面地址
	 */
	public void setCoverUrl(java.lang.String coverUrl) {
		set("coverUrl", coverUrl);
	}
	
	/**
	 * 视频封面地址
	 */
	public java.lang.String getCoverUrl() {
		return getStr("coverUrl");
	}

	/**
	 * 视频播放地址
	 */
	public void setVideoUrl(java.lang.String videoUrl) {
		set("videoUrl", videoUrl);
	}
	
	/**
	 * 视频播放地址
	 */
	public java.lang.String getVideoUrl() {
		return getStr("videoUrl");
	}

	/**
	 * 状态 0.正常 1.禁用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 0.正常 1.禁用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 排序号
	 */
	public void setSortNo(java.lang.Integer sortNo) {
		set("sortNo", sortNo);
	}
	
	/**
	 * 排序号
	 */
	public java.lang.Integer getSortNo() {
		return getInt("sortNo");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
