package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAddress<M extends BaseUserAddress<M>> extends Model<M> implements IBean {

	/**
	 * 收货地址id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 收货地址id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	/**
	 * 收货人名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 收货人名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 收货人手机号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 收货人手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 省份/自治区/直辖市
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	/**
	 * 省份/自治区/直辖市
	 */
	public java.lang.String getProvince() {
		return getStr("province");
	}

	/**
	 * 城市
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	/**
	 * 城市
	 */
	public java.lang.String getCity() {
		return getStr("city");
	}

	/**
	 * 区/县
	 */
	public void setDistrict(java.lang.String district) {
		set("district", district);
	}
	
	/**
	 * 区/县
	 */
	public java.lang.String getDistrict() {
		return getStr("district");
	}

	/**
	 * 详细地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 详细地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 地址标签
	 */
	public void setLabel(java.lang.String label) {
		set("label", label);
	}
	
	/**
	 * 地址标签
	 */
	public java.lang.String getLabel() {
		return getStr("label");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
