package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderExpress<M extends BaseOrderExpress<M>> extends Model<M> implements IBean {

	/**
	 * 订单快递信息id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 订单快递信息id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 关联的订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}
	
	/**
	 * 关联的订单号
	 */
	public java.lang.String getOrderNo() {
		return getStr("orderNo");
	}

	/**
	 * 快递名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 快递名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 查询快递链接地址
	 */
	public void setLinkUrl(java.lang.String linkUrl) {
		set("linkUrl", linkUrl);
	}
	
	/**
	 * 查询快递链接地址
	 */
	public java.lang.String getLinkUrl() {
		return getStr("linkUrl");
	}

	/**
	 * 运单号
	 */
	public void setWaybillNo(java.lang.String waybillNo) {
		set("waybillNo", waybillNo);
	}
	
	/**
	 * 运单号
	 */
	public java.lang.String getWaybillNo() {
		return getStr("waybillNo");
	}

	/**
	 * 快递包装评分
	 */
	public void setPackagingScore(java.lang.Double packagingScore) {
		set("packagingScore", packagingScore);
	}
	
	/**
	 * 快递包装评分
	 */
	public java.lang.Double getPackagingScore() {
		return getDouble("packagingScore");
	}

	/**
	 * 快递速度评分
	 */
	public void setSpeedScore(java.lang.Double speedScore) {
		set("speedScore", speedScore);
	}
	
	/**
	 * 快递速度评分
	 */
	public java.lang.Double getSpeedScore() {
		return getDouble("speedScore");
	}

	/**
	 * 快递评论内容
	 */
	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}
	
	/**
	 * 快递评论内容
	 */
	public java.lang.String getComment() {
		return getStr("comment");
	}

	/**
	 * 评价状态 0.待评价 1.已评价
	 */
	public void setScoreStatus(java.lang.Integer scoreStatus) {
		set("scoreStatus", scoreStatus);
	}
	
	/**
	 * 评价状态 0.待评价 1.已评价
	 */
	public java.lang.Integer getScoreStatus() {
		return getInt("scoreStatus");
	}

	/**
	 * 发货人id
	 */
	public void setAdminId(java.lang.Integer adminId) {
		set("adminId", adminId);
	}
	
	/**
	 * 发货人id
	 */
	public java.lang.Integer getAdminId() {
		return getInt("adminId");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
