package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsSku<M extends BaseGoodsSku<M>> extends Model<M> implements IBean {

	/**
	 * 商品规格id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 商品规格id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goodsId");
	}

	/**
	 * 规格名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 规格名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 商品属性json对象
	 */
	public void setGoodsAttr(java.lang.String goodsAttr) {
		set("goodsAttr", goodsAttr);
	}
	
	/**
	 * 商品属性json对象
	 */
	public java.lang.String getGoodsAttr() {
		return getStr("goodsAttr");
	}

	/**
	 * 价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 价格
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 原价
	 */
	public void setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("originalPrice", originalPrice);
	}
	
	/**
	 * 原价
	 */
	public java.math.BigDecimal getOriginalPrice() {
		return get("originalPrice");
	}

	/**
	 * 进价
	 */
	public void setCostPrice(java.math.BigDecimal costPrice) {
		set("costPrice", costPrice);
	}
	
	/**
	 * 进价
	 */
	public java.math.BigDecimal getCostPrice() {
		return get("costPrice");
	}

	/**
	 * 库存
	 */
	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}
	
	/**
	 * 库存
	 */
	public java.lang.Integer getStock() {
		return getInt("stock");
	}

	/**
	 * 轮播图集合id
	 */
	public void setBannersId(java.lang.Integer bannersId) {
		set("bannersId", bannersId);
	}
	
	/**
	 * 轮播图集合id
	 */
	public java.lang.Integer getBannersId() {
		return getInt("bannersId");
	}

	/**
	 * 规格排序号
	 */
	public void setSortNo(java.lang.Integer sortNo) {
		set("sortNo", sortNo);
	}
	
	/**
	 * 规格排序号
	 */
	public java.lang.Integer getSortNo() {
		return getInt("sortNo");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
