package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminMenu<M extends BaseAdminMenu<M>> extends Model<M> implements IBean {

	/**
	 * 菜单id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 菜单id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 菜单名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 菜单名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 父菜单id
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
	}
	
	/**
	 * 父菜单id
	 */
	public java.lang.Integer getParentId() {
		return getInt("parentId");
	}

	/**
	 * 页面访问路径
	 */
	public void setPagePath(java.lang.String pagePath) {
		set("pagePath", pagePath);
	}
	
	/**
	 * 页面访问路径
	 */
	public java.lang.String getPagePath() {
		return getStr("pagePath");
	}

	/**
	 * 图标字体类名
	 */
	public void setIconClass(java.lang.String iconClass) {
		set("iconClass", iconClass);
	}
	
	/**
	 * 图标字体类名
	 */
	public java.lang.String getIconClass() {
		return getStr("iconClass");
	}

	/**
	 * 排序号
	 */
	public void setSortNo(java.lang.Integer sortNo) {
		set("sortNo", sortNo);
	}
	
	/**
	 * 排序号
	 */
	public java.lang.Integer getSortNo() {
		return getInt("sortNo");
	}

	/**
	 * 创建事件
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建事件
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
