package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCart<M extends BaseCart<M>> extends Model<M> implements IBean {

	/**
	 * 购物车id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 购物车id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goodsId");
	}

	/**
	 * 规格id
	 */
	public void setSkuId(java.lang.Integer skuId) {
		set("skuId", skuId);
	}
	
	/**
	 * 规格id
	 */
	public java.lang.Integer getSkuId() {
		return getInt("skuId");
	}

	/**
	 * 商品名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 商品图片
	 */
	public void setThumbUrl(java.lang.String thumbUrl) {
		set("thumbUrl", thumbUrl);
	}
	
	/**
	 * 商品图片
	 */
	public java.lang.String getThumbUrl() {
		return getStr("thumbUrl");
	}

	/**
	 * 商品单价
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 商品单价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 商品数量
	 */
	public void setCount(java.lang.Integer count) {
		set("count", count);
	}
	
	/**
	 * 商品数量
	 */
	public java.lang.Integer getCount() {
		return getInt("count");
	}

	/**
	 * 选中状态 0.选中 1.未选中
	 */
	public void setChecked(java.lang.Integer checked) {
		set("checked", checked);
	}
	
	/**
	 * 选中状态 0.选中 1.未选中
	 */
	public java.lang.Integer getChecked() {
		return getInt("checked");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
