package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBanner<M extends BaseBanner<M>> extends Model<M> implements IBean {

	/**
	 * 横幅id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 横幅id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 类型 slide.轮播图 advert.商品横幅 promo.商品推销 category.商品类别广告
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 类型 slide.轮播图 advert.商品横幅 promo.商品推销 category.商品类别广告
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 图片地址
	 */
	public void setPictureUrl(java.lang.String pictureUrl) {
		set("pictureUrl", pictureUrl);
	}
	
	/**
	 * 图片地址
	 */
	public java.lang.String getPictureUrl() {
		return getStr("pictureUrl");
	}

	/**
	 * 链接方式 0.内链 1.外链
	 */
	public void setLinkMode(java.lang.Integer linkMode) {
		set("linkMode", linkMode);
	}
	
	/**
	 * 链接方式 0.内链 1.外链
	 */
	public java.lang.Integer getLinkMode() {
		return getInt("linkMode");
	}

	/**
	 * 外部链接地址
	 */
	public void setLinkUrl(java.lang.String linkUrl) {
		set("linkUrl", linkUrl);
	}
	
	/**
	 * 外部链接地址
	 */
	public java.lang.String getLinkUrl() {
		return getStr("linkUrl");
	}

	/**
	 * 链接的商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}
	
	/**
	 * 链接的商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goodsId");
	}

	/**
	 * 商品名称
	 */
	public void setGoodsName(java.lang.String goodsName) {
		set("goodsName", goodsName);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getGoodsName() {
		return getStr("goodsName");
	}

	/**
	 * 商品类别id,仅type等于category时需要
	 */
	public void setCategoryId(java.lang.Integer categoryId) {
		set("categoryId", categoryId);
	}
	
	/**
	 * 商品类别id,仅type等于category时需要
	 */
	public java.lang.Integer getCategoryId() {
		return getInt("categoryId");
	}

	/**
	 * 商品类别名称
	 */
	public void setCategoryName(java.lang.String categoryName) {
		set("categoryName", categoryName);
	}
	
	/**
	 * 商品类别名称
	 */
	public java.lang.String getCategoryName() {
		return getStr("categoryName");
	}

	/**
	 * 状态 0.正常 1.下架
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 0.正常 1.下架
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 排序号
	 */
	public void setSortNo(java.lang.Integer sortNo) {
		set("sortNo", sortNo);
	}
	
	/**
	 * 排序号
	 */
	public java.lang.Integer getSortNo() {
		return getInt("sortNo");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
