package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsComment<M extends BaseGoodsComment<M>> extends Model<M> implements IBean {

	/**
	 * 商品评价id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 商品评价id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 关联的订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}
	
	/**
	 * 关联的订单号
	 */
	public java.lang.String getOrderNo() {
		return getStr("orderNo");
	}

	/**
	 * 商品id
	 */
	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goodsId");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	/**
	 * 分数
	 */
	public void setScore(java.lang.Double score) {
		set("score", score);
	}
	
	/**
	 * 分数
	 */
	public java.lang.Double getScore() {
		return getDouble("score");
	}

	/**
	 * 评论内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 评论内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 分享的图片集合
	 */
	public void setPhotoUrls(java.lang.String photoUrls) {
		set("photoUrls", photoUrls);
	}
	
	/**
	 * 分享的图片集合
	 */
	public java.lang.String getPhotoUrls() {
		return getStr("photoUrls");
	}

	/**
	 * 点赞数量
	 */
	public void setLikes(java.lang.Integer likes) {
		set("likes", likes);
	}
	
	/**
	 * 点赞数量
	 */
	public java.lang.Integer getLikes() {
		return getInt("likes");
	}

	/**
	 * 显示状态 0.正常 1.隐藏
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 显示状态 0.正常 1.隐藏
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
