package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	/**
	 * 商品id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 商品id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 商品名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 商品默认图片地址
	 */
	public void setThumbUrl(java.lang.String thumbUrl) {
		set("thumbUrl", thumbUrl);
	}
	
	/**
	 * 商品默认图片地址
	 */
	public java.lang.String getThumbUrl() {
		return getStr("thumbUrl");
	}

	/**
	 * 商品默认价格
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 商品默认价格
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 商品类别id
	 */
	public void setCategoryId(java.lang.Integer categoryId) {
		set("categoryId", categoryId);
	}
	
	/**
	 * 商品类别id
	 */
	public java.lang.Integer getCategoryId() {
		return getInt("categoryId");
	}

	/**
	 * 商品品牌id
	 */
	public void setBrandId(java.lang.Integer brandId) {
		set("brandId", brandId);
	}
	
	/**
	 * 商品品牌id
	 */
	public java.lang.Integer getBrandId() {
		return getInt("brandId");
	}

	/**
	 * 商品标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 商品标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 商品介绍
	 */
	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}
	
	/**
	 * 商品介绍
	 */
	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}

	/**
	 * 预警库存
	 */
	public void setWarningStock(java.lang.Integer warningStock) {
		set("warningStock", warningStock);
	}
	
	/**
	 * 预警库存
	 */
	public java.lang.Integer getWarningStock() {
		return getInt("warningStock");
	}

	/**
	 * 单次最大购买量
	 */
	public void setMaxBuy(java.lang.Integer maxBuy) {
		set("maxBuy", maxBuy);
	}
	
	/**
	 * 单次最大购买量
	 */
	public java.lang.Integer getMaxBuy() {
		return getInt("maxBuy");
	}

	/**
	 * 商品单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 商品单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	/**
	 * 商品概述类型 0.图片 1.网页
	 */
	public void setSketchType(java.lang.Integer sketchType) {
		set("sketchType", sketchType);
	}
	
	/**
	 * 商品概述类型 0.图片 1.网页
	 */
	public java.lang.Integer getSketchType() {
		return getInt("sketchType");
	}

	/**
	 * 商品概述
	 */
	public void setSketch(java.lang.String sketch) {
		set("sketch", sketch);
	}
	
	/**
	 * 商品概述
	 */
	public java.lang.String getSketch() {
		return getStr("sketch");
	}

	/**
	 * 商品参数
	 */
	public void setSpecs(java.lang.String specs) {
		set("specs", specs);
	}
	
	/**
	 * 商品参数
	 */
	public java.lang.String getSpecs() {
		return getStr("specs");
	}

	/**
	 * 规格类型 0.单规格 1.多规格
	 */
	public void setSkuType(java.lang.Integer skuType) {
		set("skuType", skuType);
	}
	
	/**
	 * 规格类型 0.单规格 1.多规格
	 */
	public java.lang.Integer getSkuType() {
		return getInt("skuType");
	}

	/**
	 * 状态 0.上架 1.下架
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态 0.上架 1.下架
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}
	
	public java.util.Date getStartTime() {
		return get("startTime");
	}

	/**
	 * 时长
	 */
	public void setAuctionTime(java.lang.Integer auctionTime) {
		set("auctionTime", auctionTime);
	}
	
	/**
	 * 时长
	 */
	public java.lang.Integer getAuctionTime() {
		return getInt("auctionTime");
	}

	/**
	 * 0 拍卖 1 正常
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 0 拍卖 1 正常
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
