package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	/**
	 * 订单id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 订单id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}
	
	/**
	 * 订单号
	 */
	public java.lang.String getOrderNo() {
		return getStr("orderNo");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	/**
	 * 订单状态 0.已下单 2.已付款 4.已配货 6.已发货 8.已收货 10.已评价 30.退款中 32.已退款 34.退款失败 40.已取消
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 订单状态 0.已下单 2.已付款 4.已配货 6.已发货 8.已收货 10.已评价 30.退款中 32.已退款 34.退款失败 40.已取消
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 商品总金额
	 */
	public void setGoodsAmount(java.math.BigDecimal goodsAmount) {
		set("goodsAmount", goodsAmount);
	}
	
	/**
	 * 商品总金额
	 */
	public java.math.BigDecimal getGoodsAmount() {
		return get("goodsAmount");
	}

	/**
	 * 快递费
	 */
	public void setExpressFee(java.math.BigDecimal expressFee) {
		set("expressFee", expressFee);
	}
	
	/**
	 * 快递费
	 */
	public java.math.BigDecimal getExpressFee() {
		return get("expressFee");
	}

	/**
	 * 订单总金额
	 */
	public void setTotalAmount(java.math.BigDecimal totalAmount) {
		set("totalAmount", totalAmount);
	}
	
	/**
	 * 订单总金额
	 */
	public java.math.BigDecimal getTotalAmount() {
		return get("totalAmount");
	}

	/**
	 * 优惠金额
	 */
	public void setDiscountAmount(java.math.BigDecimal discountAmount) {
		set("discountAmount", discountAmount);
	}
	
	/**
	 * 优惠金额
	 */
	public java.math.BigDecimal getDiscountAmount() {
		return get("discountAmount");
	}

	/**
	 * 实付金额
	 */
	public void setPayAmount(java.math.BigDecimal payAmount) {
		set("payAmount", payAmount);
	}
	
	/**
	 * 实付金额
	 */
	public java.math.BigDecimal getPayAmount() {
		return get("payAmount");
	}

	/**
	 * 支付方式 0.支付宝 1.微信
	 */
	public void setPayMode(java.lang.Integer payMode) {
		set("payMode", payMode);
	}
	
	/**
	 * 支付方式 0.支付宝 1.微信
	 */
	public java.lang.Integer getPayMode() {
		return getInt("payMode");
	}

	/**
	 * 支付平台 0.pc 1.app 2.小程序 3.手机H5
	 */
	public void setPayPlatform(java.lang.Integer payPlatform) {
		set("payPlatform", payPlatform);
	}
	
	/**
	 * 支付平台 0.pc 1.app 2.小程序 3.手机H5
	 */
	public java.lang.Integer getPayPlatform() {
		return getInt("payPlatform");
	}

	/**
	 * 请求付款时设备ip地址
	 */
	public void setIpAddress(java.lang.String ipAddress) {
		set("ipAddress", ipAddress);
	}
	
	/**
	 * 请求付款时设备ip地址
	 */
	public java.lang.String getIpAddress() {
		return getStr("ipAddress");
	}

	/**
	 * 付款平台的支付单号
	 */
	public void setPaymentNo(java.lang.String paymentNo) {
		set("paymentNo", paymentNo);
	}
	
	/**
	 * 付款平台的支付单号
	 */
	public java.lang.String getPaymentNo() {
		return getStr("paymentNo");
	}

	/**
	 * 订单备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 订单备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	/**
	 * 1 正常
2竞拍
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 1 正常
2竞拍
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}
	
	public java.lang.Integer getGoodsId() {
		return getInt("goodsId");
	}

}
