package top.chengdongqing.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderAddress<M extends BaseOrderAddress<M>> extends Model<M> implements IBean {

	/**
	 * 订单收货信息id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 订单收货信息id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 关联的订单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}
	
	/**
	 * 关联的订单号
	 */
	public java.lang.String getOrderNo() {
		return getStr("orderNo");
	}

	/**
	 * 收货人姓名
	 */
	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}
	
	/**
	 * 收货人姓名
	 */
	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	/**
	 * 收货人手机号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 收货人手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 省份/自治区/直辖市
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	/**
	 * 省份/自治区/直辖市
	 */
	public java.lang.String getProvince() {
		return getStr("province");
	}

	/**
	 * 城市
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	/**
	 * 城市
	 */
	public java.lang.String getCity() {
		return getStr("city");
	}

	/**
	 * 区/县
	 */
	public void setDistrict(java.lang.String district) {
		set("district", district);
	}
	
	/**
	 * 区/县
	 */
	public java.lang.String getDistrict() {
		return getStr("district");
	}

	/**
	 * 详细地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 详细地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
